server:
  port: 8084
  servlet:
    encoding:
      force-response: true

logging:
  level:
    com.boot.first: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basicjpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true
      highlight_sql: true

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul